version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - '8000:80'
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: 'db_test'
      MYSQL_USER: 'user_test'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
